/*
 * File: app/store/Quizes.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.Quizes', {
    extend: 'Ext.data.TreeStore',

    requires: [
        'MyApp.model.Quiz'
    ],

    config: {
        model: 'MyApp.model.Quiz',
        storeId: 'MyJsonTreeStore',
        defaultRootProperty: 'items',
        root: {
            text: 'Available Quizes',
            items: [
                {
                    text: 'Sample Quiz',
                    items: [
                        {
                            text: 'What is when 2 added to 5',
                            items: [
                                {
                                    text: '1',
                                    leaf: true
                                },
                                {
                                    text: '2',
                                    leaf: true
                                }
                            ]
                        },
                        {
                            text: 'Will sun shine tomorrow?',
                            items: [
                                {
                                    text: 'Yes',
                                    leaf: true
                                },
                                {
                                    text: 'No',
                                    leaf: true
                                }
                            ]
                        }
                    ]
                },
                {
                    text: 'Fruit',
                    items: [
                        {
                            text: 'Bananas',
                            leaf: true
                        },
                        {
                            text: 'Lemon',
                            leaf: true
                        }
                    ]
                },
                {
                    text: 'Snacks',
                    items: [
                        {
                            text: 'Nuts',
                            leaf: true
                        },
                        {
                            text: 'Pretzels',
                            leaf: true
                        },
                        {
                            text: 'Wasabi Peas',
                            leaf: true
                        }
                    ]
                }
            ]
        }
    }
});